apiVersion: v1
kind: Secret
metadata:
    name: ascoachingogvaner-admin-code
    namespace: ascoachingogvaner
type: Opaque
stringData:
    ADMIN_CODE: ENC[AES256_GCM,data:F99sTKw0BN3hLYxSjMJD13etb/c=,iv:yTpFhu47J+RD/QL4aVt86Cyr0DwVeqNZImlHliLFOw8=,tag:KOAk5eTsNiNcYOs7tfNGPw==,type:str]
    NOTIFY_EMAIL: ENC[AES256_GCM,data:6EQoUwPW+e3ttblWiRn5geOY,iv:0aaLrLfgC1dUk4P7lTPN3j0s7QLY6BHcw7ZiPL032Bs=,tag:tuJqV/ecMoaqokvXE9RAbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOWtOanh0ckNBUWhBSHpl
            UGdKVUZ3eDhDbFhWemNLYW8weHBWTzdHclE4CmZiU09lK0JBU2lSTEZ6dEtmRmVC
            dDUxb2ZrVXc5cjJNaXA3d2FqbmQyaWMKLS0tIDFFSTFwL2xTU292WldDSkJHWmdp
            YzUzTkNEbnpSeG5XeVZhN05IdXV4QkkKT+tpvqJi+k58nKYv52vD3nBd3QqO+OzX
            yk4zOH7xfp4YZ/k7/4/SXlAGo3DBOWUFUmKIQrtrkBpCPIafArDRLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h9hu65zr3ahk4wcv3ftvvgqca0kzdm0jucx609a0s9qs9ax8r4hss0n3n8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T02:44:47Z"
    mac: ENC[AES256_GCM,data:4oo0DETNM4vd3U3IXDWWRSVgIpxSgguiq9fo1si47KyGOjDQV4VsOwMWYI/wwt7jeUpKJcisw6gNJ/w8V9q+8M+gJ4p5CoJSRVtp7eD7buvnqhfK8hR30ovwcLeyW0J4vXUkil8uzb7BPfvw1MXZVCAM+AtYxLTV8oIt1r4atso=,iv:QhMmFXim5sOBYnI50Z7vD+pU4jLLIE6lfL101dSijRE=,tag:1SGA9H7grkU3DhJEJ2xvKw==,type:str]
    version: 3.13.1
