apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - external-dns-deployment.yaml
  - external-dns-serviceaccount.yaml
  - httproute.yaml
  - httproute-www.yaml
  - service.yaml
  - simply-credentials-externalsecret.yaml
